name: Run on tag

on:
  push:
    tags:
      - "v*"

jobs:
  create-tag:
    runs-on: ubuntu-18.04

    steps:
     
      - name: Create tag
        uses: ./actions/tag
        with:
          version: "FIVE"
          message: "practice tagging"
