name: Run on tag

on:
  push:
    tags:
      - "v*"

jobs:
  create-tag:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: ls

      - name: Create tag
        uses: ./.github/actions/tag
        with:
          version: "FIVE"
          message: "practice tagging"
